name: node-candidate
services:
  api:
    container_name: node-candidate-api
    build: { context: . , dockerfile: apps/api/Dockerfile }
    ports: ['3003:3000']
  postgres:
    container_name: node-candidate-db
    image: postgres:15
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: challenge_db
